[pytest]
xfail_strict = true
faulthandler_timeout = 60
junit_family = xunit2
trio_mode = true
trio_run = qtrio
# https://github.com/python-trio/pytest-trio/issues/128
filterwarnings =
    ignore:trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead:trio.TrioDeprecationWarning
